# Generated by Django 5.2.3 on 2025-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='montantsalaire',
            name='salaire_hebdomadaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='montantsalaire',
            name='salaire_horaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='montantsalaire',
            name='salaire_journalier',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='montantsalaire',
            name='salaire_mensuel',
            field=models.FloatField(default=0.0),
        ),
    ]
