# Generated by Django 5.2.3 on 2025-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0002_montantsalaire_salaire_hebdomadaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.TextField(blank=True, choices=[('INFO', 'Information'), ('LOG', 'Evenement')], null=True),
        ),
    ]
