# Generated by Django 5.2.3 on 2025-06-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0003_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.TextField(blank=True, choices=[('INFO', 'Information'), ('WARNING', 'attention'), ('SUCCESS', 'succes'), ('ERROR', 'erreur'), ('LOG', 'Evenement')], default='INFO', null=True),
        ),
    ]
