# Generated by Django 5.2.3 on 2025-06-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0004_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='id_cat_depense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetManager.categoriedepense'),
        ),
    ]
