# Generated by Django 5.2.3 on 2025-06-20 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0005_alter_depense_id_cat_depense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='montantsalaire',
            options={'verbose_name': 'Configuration des salaires', 'verbose_name_plural': 'Configurations des salaires'},
        ),
        migrations.AddField(
            model_name='montantsalaire',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='montantsalaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
